[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anzen-client"
version = "0.1.0"
description = "Anzen Client - React/Next.js frontend for the Anzen Safe Agentic Workflows platform"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Anzen Team", email = "team@anzen.dev"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.6",
    "aiofiles>=23.2.0",
    "httpx>=0.25.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.0.0",
    "structlog>=23.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.25.0",
    "pytest-mock>=3.12.0",
    "coverage>=7.3.0",
]

[project.scripts]
anzen-client = "anzen_client.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/anzen_client"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    "/static",
    "/templates",
    "/README.md",
]
